# Generated by Django 4.1.10 on 2023-08-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgahawa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='Product',
        ),
    ]
