# Generated by Django 4.1.10 on 2023-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgahawa', '0003_fooditem_alter_orderitem_item_delete_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
