# Generated by Django 4.1.10 on 2023-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgahawa', '0004_alter_fooditem_description_alter_fooditem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
